---
- name: "show folder"
  shell: |
    ls -lh

- name: Copy index test page
  template:
    src: "/project"
    dest: "/"

- name: "Extract Artifact"
  shell: |
    tar -xvfz artifact.tar.gz

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start

