---
- name: Copy artifact.tar.gz to EC2
  template:
    src: "files/artifact.tar.gz"
    dest: "~/artifact.tar.gz"

- name: "Extract Artifact"
  shell: |
    cd ~/
    tar -xvfz artifact.tar.gz

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start

