---
- name: Copy artifact.tar.gz to EC2
  template:
    src: "files/artifact.tar.gz"
    dest: "/home/ubuntu/artifact.tar.gz"

- name: Executing node
  shell: |
    cd /home/ubuntu/
    tar -xvfz artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start

